services:
  vault:
    container_name: vault
    image: hashicorp/vault:1.17
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    ports:
      - 8201:8200
    volumes:
      - type: bind
        source: ./config.hcl
        target: /vault/config/config.hcl

    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl